version: '3.2'
services:
  plugin:
    image: quay.io/arcalot/arcaflow-plugin-coremark-pro
    build: .
    volumes:
      - source: ./inputs/example.yaml
        target: /config/example.yaml
        type: bind
